- go.mod
The go.sum file should be checked-in to the repo so we can have
repeatable builds.
> Update go.mod and check-in go.sum

- pkg/nutanix/v3/v3_service.go
Adding getCurrentLoggedInUser in order to get details on the user account used to invoke the API calls.
> adding GetCurrentLoggedInUser function

- CHANGELOG.md
- Makefile
- go.mod
- go.sum
- pkg/nutanix/fc/fc.go
- pkg/nutanix/fc/fc_service.go
- pkg/nutanix/fc/fc_service_test.go
- pkg/nutanix/fc/fc_structs.go
- pkg/nutanix/fc/fc_test.go
Move over fc stubs from nutanix/terraform-provider-nutanix.
> Check-in the fc stubs

- CHANGELOG.md
- Makefile
- pkg/nutanix/karbon/karbon_api.go
- pkg/nutanix/karbon/karbon_api_test.go
- pkg/nutanix/karbon/karbon_cluster_service.go
- pkg/nutanix/karbon/karbon_cluster_structs.go
- pkg/nutanix/karbon/karbon_meta_service.go
- pkg/nutanix/karbon/karbon_meta_structs.go
- pkg/nutanix/karbon/karbon_private_registry_service.go
- pkg/nutanix/karbon/karbon_private_registry_structs.go
Move over karbon stubs from nutanix/terraform-provider-nutanix.
> Check-in the karbon stubs

- CHANGELOG.md
Prepare the CHANGELOG for v0.2.0 release.
> Update version in CHANGELOG.md

- .github/workflows/codeql-analysis.yaml
- .github/workflows/synopsys.yaml
Implement GitHub action security scan against Blackduck and CodeQL
> implement security scan workflow

- .github/workflows/makefile.yml
The workflow runs the build targets in Makefile:
- vendor
- build
- lint
- test
- coverage
> Create Makefile workflow for GitHub actions

- Makefile
- client.go
- client_test.go
- fc/fc_service.go
- fc/fc_service_test.go
- fc/fc_structs.go
- foundation/foundation_api.go
- foundation/foundation_file_management_service.go
- foundation/foundation_node_imaging_service.go
- foundation/foundation_node_imaging_service_test.go
- foundation/foundation_structs.go
- karbon/karbon_cluster_structs.go
- v3/v3_service.go
- v3/v3_service_test.go
- v3/v3_structs.go
Enable gofumpt checks to the lint target in Makefile.
> Add gofumpt checks while linting

- .github/workflows/build-lint-test.yml
> Bump golangci-lint timeout

- CHANGELOG.md
- internal/client.go
- v3/v3.go
- v3/v3_test.go
Add functional options to v3 client constructor
and add a WithCertificate option.
> Refactor v3 client constructor

- CHANGELOG.md
- v3/v3_service.go
- v3/v3_service_test.go
Propagate context instead of using context.TODO.
> Add context to v3 interface

- CHANGELOG.md
- v3/v3.go
This will allow users to inject a custom logr.Logger
> Add `WithLogger` functional option for v3 client

- CHANGELOG.md
- go.mod
- go.sum
- internal/client.go
This allows us to use multiple certificates using the `WithCertificate` option.
> Store certpool inside the client object

- .github/workflows/build-lint-test.yml
- CHANGELOG.md
- Makefile
- environment/credentials/types.go
Use semi-colon to separate out enum values
> Fix the kubebuilder enum

- README.md
> Modify the README.md

- karbon/karbon_cluster_registration_service_test.go
- karbon/mocks/TestKarbonCreateClusterRegistration.yaml
- karbon/mocks/TestKarbonGetK8sRegistrationList.yaml
Update the Unit Test based on https://jira.nutanix.com/browse/KRBN-6345
> KRBN-6345: Update the Unit Test based on KRBN-6345

- CHANGELOG.md
- karbon/karbon_cluster_registration_service.go
- karbon/karbon_cluster_registration_service_test.go
- karbon/karbon_cluster_registration_structs.go
- karbon/mocks/TestKarbonCreateClusterRegistrationAndAddonSetInfo.yaml
- karbon/mocks/TestKarbonCreateClusterRegistrationAndSetInfo.yaml
Added cluster info register and addon info register apis and their tests
"make test" passes
> Added apis and tests for setInfo and addon setinfo

- CHANGELOG.md
- v3/v3_service_test.go
- v3/v3_structs.go
Enhanced the RecoveryPlan-related struct to allow for specifying the category of volume groups to be included and to allow for specifying the cluster/AZ list.
> Enhanced the RecoveryPlan-related struct.

- CHANGELOG.md
> Update CHANGELOG.md to prepare for 0.4.0 release

- v3/cache.go
- v3/cache_test.go
- v4/cache.go
- v4/cache_test.go
adding defensive code to avoid panic
> fix(bug): adding defensive code to avoid panic (#257)

- converged/anti_affinity_policies.go
- converged/converged.go
- converged/storage_containers.go
- converged/subnets.go
- converged/v4/anti_affinity_policies.go
- converged/v4/storage_containers.go
- converged/v4/structs.go
- converged/v4/subnets.go
Storage Container interfaces
- interfaces and placeholders
6th PR in Stacked PRs
Previous PR: https://github.com/nutanix-cloud-native/prism-go-client/pull/269
Next PR: https://github.com/nutanix-cloud-native/prism-go-client/pull/272
> feat: (PR6) Converged Client: Storage Container interfaces
